### ISSUE TITLE
Integração direta do painel de ajuste de temperatura em um card do Home Assistant

### ISSUE THREAD

**Issue by carlosptf** [mukaschultze/ha-aquecedor-rinnai#25]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/mukaschultze/ha-rinnai-heater/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Atualmente, o painel de ajuste de temperatura funciona somente por meio de um popup que aparece após clicar no botão do aquecedor. Isso torna o processo de ajuste mais lento e menos intuitivo, exigindo uma ação extra do usuário para acessar as configurações.

### Describe the solution you'd like

Gostaria que o painel de ajuste de temperatura pudesse ser vinculado diretamente a um card de controle no Home Assistant, permitindo a alteração da temperatura sem a necessidade de abrir um popup. Essa melhoria traria uma experiência mais fluida e integrada, compatível com a interface dos outros dispositivos do Home Assistant.

### Describe alternatives you've considered

Tentei personalizar a interface para que o popup fosse aberto automaticamente ou que o painel fosse embutido no card, mas sem sucesso. No momento, não há uma alternativa que permita o ajuste direto de forma simples e intuitiva.

### Additional context

Acredito que essa funcionalidade facilitaria o uso do plugin, otimizando o fluxo de interação e melhorando a experiência do usuário. Se necessário, posso fornecer mais detalhes ou prints da interface atual para melhor ilustrar a necessidade.

**Comment by mukaschultze** [comment]
![Image](https://github.com/user-attachments/assets/f4752570-a685-4c96-94e1-8f1473465b55)

```yaml
features:
  - type: target-temperature
  - type: water-heater-operation-modes
type: tile
entity: water_heater.e21_heater
grid_options:
  rows: auto
  columns: full
state_content:
  - state
  - current_temperature
features_position: bottom
vertical: false

```
